/**
 * Androgenic Web — Guides content
 * Full, science-aware looksmaxxing guides. Free guides are open;
 * `pro:true` guides are gated behind the paywall.
 */
const GUIDES = [
  {
    id: 'jaw',
    emoji: '🦴',
    title: 'Jawline & Mewing',
    tag: 'Bone structure',
    minutes: 6,
    pro: false,
    summary: 'Build a sharper, more defined jaw with posture, training and body composition.',
    sections: [
      { h: 'What actually moves the needle', p: 'Three levers control how your jaw reads: body-fat %, masseter development, and tongue/head posture. Genetics set the ceiling, but most people are nowhere near theirs.' },
      { h: 'Mewing — proper tongue posture', p: 'Rest the entire tongue flat against the roof of your mouth — the back third is the part most people miss. Lips sealed, teeth lightly touching, breathe through your nose 24/7. It is a habit, not a workout: consistency over months is what matters.' },
      { h: 'Train the masseter', p: 'Chew tough gum (falim, then mastic) 20–40 min/day, evenly on both sides. Progress like any muscle — start light, add time, rest. This widens and sharpens the jaw angle.' },
      { h: 'Reveal the bone', p: 'The jaw is the first place definition shows when you drop body fat. Target 10–15%. Cut sodium and alcohol to kill facial bloat, drink 3L+ water, and sleep elevated.' },
      { h: 'Fix forward-head posture', p: 'A jutting head hides the jaw and submental area. Do chin tucks, strengthen deep neck flexors, and set screens at eye level. This alone can transform your side profile.' },
    ],
    checklist: ['Mew all day', 'Chew gum 20–40 min', 'Sleep on your back', 'Cut sodium', '3L+ water', 'Chin tucks daily'],
  },
  {
    id: 'eyes',
    emoji: '👀',
    title: 'Hunter Eyes & Eye Area',
    tag: 'Eye area',
    minutes: 5,
    pro: false,
    summary: 'Reduce eye-area aging and create the coveted positive canthal tilt look.',
    sections: [
      { h: 'Sleep is the #1 lever', p: '7–9 hours, on your back, head slightly elevated. Poor sleep is the fastest way to destroy the under-eye area with bags, dark circles and hollowing.' },
      { h: 'Kill dark circles', p: 'Caffeine eye cream + cold compress in the morning, vitamin K / vitamin C at night. Treat allergies (antihistamines, nasal rinse) — "allergic shiners" are very common.' },
      { h: 'The squinch / hunter eyes', p: 'Engage the lower eyelid slightly (a soft squint, not a smile). It creates a positive canthal tilt look in photos and trains the orbicularis over time.' },
      { h: 'Brows frame everything', p: 'Clean strays under the brow, keep natural thickness on top, and let a slight arch form. Never over-pluck — full, groomed brows out-perform thin ones every time.' },
      { h: 'Protect the area', p: 'Daily SPF around the eyes, sunglasses outdoors to stop squint-aging, and never rub your eyes — the skin there is the thinnest on your face.' },
    ],
    checklist: ['7–9h back-sleep', 'Caffeine eye cream AM', 'Practice the squinch', 'Groom brows', 'SPF + sunglasses'],
  },
  {
    id: 'skin',
    emoji: '✨',
    title: 'Skin Glow-Up',
    tag: 'Skin quality',
    minutes: 7,
    pro: false,
    summary: 'A clear, even, healthy complexion is the strongest halo effect in attractiveness.',
    sections: [
      { h: 'The minimum effective routine', p: 'AM: gentle cleanser → moisturizer → SPF 30+. PM: cleanser → treatment → moisturizer. Consistency beats expensive products every time.' },
      { h: 'Sunscreen is non-negotiable', p: 'UV is the #1 cause of premature aging. SPF 30–50 daily, even when cloudy. This single habit out-performs every serum combined.' },
      { h: 'Add a retinoid', p: 'Tretinoin / retinol is the gold standard — boosts cell turnover, clears acne, fades scars, smooths texture. Start 0.025% twice a week and ramp slowly. Always buffer with moisturizer.' },
      { h: 'Level-up actives', p: 'Vitamin C in the morning (antioxidant + brightening), niacinamide (pores + barrier), and a weekly AHA/BHA exfoliant. Add hyaluronic acid for plumpness.' },
      { h: 'Diet & habits', p: 'Cut dairy and high-glycemic spikes if acne-prone, eat omega-3s, hydrate, change pillowcases every 2–3 days, and never pick.' },
    ],
    checklist: ['Cleanse AM/PM', 'SPF every morning', 'Retinoid at night', 'Vitamin C AM', 'Exfoliate weekly'],
  },
  {
    id: 'hair',
    emoji: '💇',
    title: 'Hair Maxxing',
    tag: 'Hair & hairline',
    minutes: 5,
    pro: false,
    summary: 'Thicker, healthier hair and a cut that actually frames your face.',
    sections: [
      { h: 'Stop over-washing', p: 'Shampoo strips natural oils — use it 2–3x/week and condition the rest. Finish with a cold rinse to seal the cuticle for shine and reduced frizz.' },
      { h: 'Defend the hairline early', p: 'If you see thinning, see a dermatologist about finasteride (blocks DHT) and minoxidil (stimulates growth). Early intervention is everything — these work best before major loss.' },
      { h: 'Stimulate growth', p: 'Daily 5–10 min scalp massage (rosemary oil optional) and a weekly 1.5mm dermaroller boost circulation and growth factors — strong synergy with minoxidil.' },
      { h: 'Feed your follicles', p: 'Biotin, adequate iron & zinc, and enough protein (hair is keratin). Deficiencies are a common, fixable cause of poor hair.' },
      { h: 'The right cut > everything', p: 'Find a barber who reads face shapes, bring reference photos, and trim every 3–4 weeks. The correct cut can swing your overall look 1–2 points.' },
    ],
    checklist: ['Wash 2–3x/week', 'Cold rinse', 'Scalp massage daily', 'Dermaroll weekly', 'Fresh cut q3–4 wks'],
  },
  {
    id: 'test',
    emoji: '💪',
    title: 'Testosterone Optimization',
    tag: 'Masculinity',
    minutes: 6,
    pro: true,
    summary: 'Natural levers for higher T — driving stronger masculine features and recovery.',
    sections: [
      { h: 'Sleep & stress', p: 'The biggest natural levers. 7–9h of quality sleep and managed cortisol have an outsized effect on free testosterone. Fix these before chasing supplements.' },
      { h: 'Train heavy & compound', p: 'Squats, deadlifts, bench, overhead press, rows. Heavy compound lifting with progressive overload drives the hormonal and structural adaptations you want.' },
      { h: 'Micronutrients that matter', p: 'Vitamin D (get sun / supplement), zinc, and magnesium are the three deficiencies most tied to low T. Cover these first.' },
      { h: 'Body composition', p: 'Excess body fat aromatizes testosterone into estrogen. Getting to 10–15% body fat improves both your hormones and how your face reads.' },
      { h: 'Kill the killers', p: 'Minimize alcohol, avoid chronic sleep debt, limit ultra-processed seed-oil-heavy food, and don’t crash-diet on calories or fat.' },
    ],
    checklist: ['7–9h sleep', 'Heavy compounds 3–4x', 'Vit D + zinc + mag', 'Manage stress', 'Limit alcohol'],
  },
  {
    id: 'supps',
    emoji: '💊',
    title: 'Supplement Stack',
    tag: 'Supplements',
    minutes: 5,
    pro: true,
    summary: 'An evidence-leaning stack for skin, hair, recovery and overall optimization.',
    sections: [
      { h: 'Foundational', p: 'Vitamin D3 (2000–4000 IU), Omega-3 fish oil (EPA/DHA), Magnesium glycinate, and Zinc. These cover the most common deficiencies that affect skin, hair, sleep and T.' },
      { h: 'Skin & hair', p: 'Collagen peptides (10g), Biotin (skin/hair/nails), and Vitamin C (collagen synthesis + antioxidant). Hydration and SPF still matter more.' },
      { h: 'Performance & recovery', p: 'Creatine monohydrate (5g daily — the most researched supplement there is), and Ashwagandha for stress/cortisol and sleep quality.' },
      { h: 'How to run it', p: 'Add one at a time so you can judge effects. Take fat-solubles (D3, fish oil) with food. Most effects compound over weeks, not days — be patient and consistent.' },
    ],
    checklist: ['Vit D3', 'Omega-3', 'Magnesium', 'Zinc', 'Creatine 5g', 'Collagen + Vit C'],
  },
  {
    id: 'mindset',
    emoji: '🧠',
    title: 'Mindset & Confidence',
    tag: 'Inner game',
    minutes: 4,
    pro: true,
    summary: 'Looks open the door — presence and confidence are what people remember.',
    sections: [
      { h: 'Posture is instant looksmaxxing', p: 'Shoulders back, chest open, chin level, eyes up. Good posture changes your jaw, neck and silhouette immediately — and how others read your status.' },
      { h: 'Slow is dominant', p: 'Unhurried movement, steady eye contact and a relaxed face signal security. Rushing and fidgeting signal the opposite.' },
      { h: 'Stack small wins', p: 'Confidence is evidence-based. Train, keep your streak, complete your routine — each kept promise to yourself compounds into genuine self-belief.' },
      { h: 'Detach from the number', p: 'Use your scores as a map, not a verdict. The goal is steady self-improvement, not obsession. The people who win treat it as a long game.' },
    ],
    checklist: ['Fix posture', 'Slow your movements', 'Daily eye contact', 'Keep your streak', 'Play the long game'],
  },
  {
    id: 'symmetry',
    emoji: '📐',
    title: 'Symmetry & Posture',
    tag: 'Symmetry',
    minutes: 4,
    pro: true,
    summary: 'Even out left/right imbalances with sleep, chewing and postural fixes.',
    sections: [
      { h: 'Back-sleep for balance', p: 'Years of side-sleeping compresses one side of the face. Transition to back-sleeping with a supportive pillow — one of the most impactful symmetry fixes.' },
      { h: 'Chew evenly', p: 'Most people favor one side, building an asymmetric masseter. Consciously alternate; in gum training, give equal time to each side, with extra reps on the weaker side.' },
      { h: 'Correct the body', p: 'Uneven shoulders, head tilt and scoliosis pull the face out of balance. A PT or corrective-exercise routine for posture gradually improves facial balance too.' },
      { h: 'Even tongue pressure', p: 'When mewing, apply equal force on both sides of the palate — lopsided pressure can reinforce asymmetry.' },
    ],
    checklist: ['Back-sleep', 'Alternate chewing', 'Posture work', 'Even mewing pressure'],
  },
];

function getGuide(id) { return GUIDES.find(g => g.id === id); }
